name = str(input("What is your name ?\n"))
surname = str(input("What is your surname ?\n"))
clas = int(input("In which class do you study ?\n"))
school = str(input("What is your school name ?\n"))
father = str(input("What is your father name ?\n"))
mother = str(input("What is your mother name ?\n"))
print("THANKYOU FOR YOUR INFORMATION !")

f = open("student.txt", "a")
f.write(f"\n-----------------------------------------------\n {name}\n{surname}\n{clas}\n{school}\n{father}\n{mother}")
f.close()